# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [8]:
# Import torch
import torch

# Create random tensor
random_tensor1 = torch.rand(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
random_tensor2 = torch.rand(1,7)

# Perform matrix multiplication 
random_tensor2_transpose = torch.transpose(random_tensor2,0,1)
torch.matmul(random_tensor1,random_tensor2_transpose)

tensor([[1.5002],
        [1.6748],
        [1.6879],
        [1.4221],
        [1.1984],
        [1.9292],
        [1.2020]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [29]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor3 = torch.rand(7, 7)
tensor4 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor3,tensor4.T),torch.matmul(tensor3,tensor4.T).shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
if torch.cuda.is_available():  
    device = "cuda"
elif torch.backends.mps.is_available():  
    device = "mps"
else:
    device = "cpu"

print(device)
torch.backends.mps.manual_seed(1234) # 报错因为mps并不需要专门设置seeds

mps


AttributeError: module 'torch.backends.mps' has no attribute 'manual_seed'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.backends.mps.is_available()

# Create two random tensors on GPU
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)
tensor_to_gpu1 = tensor1.to(device)
tensor_to_gpu2 = tensor2.to(device)
tensor_to_gpu1,tensor_to_gpu2


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
print(tensor_to_gpu1@tensor_to_gpu2.T)

tensor_to_gpu2_transpose = torch.transpose(tensor_to_gpu2,0,1)
multiplication = torch.matmul(tensor_to_gpu1,tensor_to_gpu2_transpose)
multiplication,multiplication.shape

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
max = torch.max(multiplication)

# Find min
min = torch.min(multiplication)

max,min

(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max
arg_max = torch.argmax(multiplication)

# Find arg min
arg_min = torch.argmin(multiplication)

arg_max,arg_min

(tensor(-9223372036854775808, device='mps:0'),
 tensor(-9223372036854775808, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeeze = torch.squeeze(random)

# Print out tensors and their shapes
print(random,random.shape)
print(squeeze,squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
